name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Lint code
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Build application
        run: npm run build

      - name: Test build output
        run: |
          # Verify build artifacts exist
          test -d .next || (echo "Build output missing" && exit 1)
          test -f public/data/projects.json || (echo "Projects data missing" && exit 1)
          echo "Build verification passed"

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Check for known vulnerabilities
        run: |
          # Check for common security issues
          if grep -r "process\.env\." src/ --include="*.ts" --include="*.tsx" | grep -v "process.env.NODE_ENV"; then
            echo "Warning: Found potential environment variable exposure"
          fi

          if grep -r "dangerouslySetInnerHTML" src/ --include="*.tsx"; then
            echo "Info: Found dangerouslySetInnerHTML usage (review for XSS)"
          fi
